services:

  mlflow_db:
    restart: always
    image: mysql/mysql-server@sha256:5b40d96b11333570143d98d3a74100fefadb9abb17b27a95dbc9ad33544ec142
    env_file:
      - .env
    container_name: mlflow_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mlflow_db_data:/var/lib/mysql
    networks:
      - recsys

  mlflow_server:
    restart: always
    build: mlflow/
    image: mlflow_server
    container_name: mlflow_server
    depends_on:
      - mlflow_db
    env_file:
      - .env
    ports:
      - "5002:5000"
    environment:
      - MLFLOW_ALLOWED_HOSTS=*
      - MLFLOW_CORS_ORIGINS=*
      - MLFLOW_HTTP_REQUEST_MAX_RETRIES=3
      - MLFLOW_HTTP_REQUEST_POOL_MAXSIZE=50
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MLFLOW_S3_ENDPOINT_URL=https://s3.ap-southeast-2.amazonaws.com
      - GUNICORN_CMD_ARGS=--timeout 300 --forwarded-allow-ips="*" --proxy-allow-from="*"
    command: >
      mlflow server
        --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mlflow_db:3306/${MYSQL_DATABASE}
        --artifacts-destination s3://${AWS_BUCKET_NAME}
        --host 0.0.0.0
        --port 5000
        --allowed-hosts="*"
    networks:
      - recsys

  redis:
    # Redis is limited to 7.2-bookworm due to licencing change
    # https://redis.io/blog/redis-adopts-dual-source-available-licensing/
    image: redis:7.2-bookworm
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./data/redis:/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    networks:
      - recsys

  qdrant:
    image: qdrant/qdrant:v1.12.0
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant_storage:/qdrant/storage:z
    restart: always
    networks:
      - recsys

  dwh:
    container_name: dwh
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
    volumes:
       - ./data/postgres:/data/postgres
       # Run scripts to create schemas upon startup
       - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow", "-p", "5432"]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - recsys

  feature_online_server:
    container_name: feature_online_server
    build:
      context: .
      dockerfile: feature_pipeline.Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=dwh
    ports:
      - "${FEAST_ONLINE_SERVER_PORT:-8815}:${FEAST_ONLINE_SERVER_PORT:-6566}"
    working_dir: /app/feature_pipeline/feast/feature_repo
    entrypoint: ["uv", "run", "feast", "serve", "--port", "${FEAST_ONLINE_SERVER_PORT:-6566}", "--host", "0.0.0.0"]
    networks:
      - recsys

  feature_offline_server:
    container_name: feature_offline_server
    build:
      context: .
      dockerfile: feature_pipeline.Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=dwh
    ports:
      - "${FEAST_OFFLINE_SERVER_PORT:-8815}:${FEAST_OFFLINE_SERVER_PORT:-8815}"
    working_dir: /app/feature_pipeline/feast/feature_repo
    entrypoint: ["uv", "run", "feast", "serve_offline", "--port", "${FEAST_OFFLINE_SERVER_PORT:-8815}", "--host", "0.0.0.0"]
    networks:
      - recsys

  feature_store_ui:
    container_name: feature_store_ui
    build:
      context: .
      dockerfile: feature_pipeline.Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=dwh
    ports:
      - "${FEAST_UI_PORT:-8887}:${FEAST_UI_PORT:-8887}"
    working_dir: /app/feature_pipeline/feast/feature_repo
    entrypoint: ["uv", "run", "feast", "ui", "--port", "${FEAST_UI_PORT:-8887}", "--host", "0.0.0.0"]
    networks:
      - recsys

networks:
  recsys:
    name: recsys
    driver: bridge

volumes:
  mlflow_db_data: